services:
  peachfuzz:
    build:
      context: .
      dockerfile: Dockerfile
      target: execute
    image: peachfuzz:latest
    environment:
      TZ: UTC
      DBPATH: /app/data/peachfuzz.db
    ports:
      - "8000:8000"
    volumes:
      - db:/app/data
    restart: unless-stopped

volumes:
  db:
